### ISSUE TITLE
Facing issue while running the code in jupyter notebook

### ISSUE THREAD

**Issue by utkarsh-tyagi** [FHPythonUtils/SvgTrace#1]
I have tried to run this project in jupyter notebook but it give me error:

ElementHandleError: Evaluation failed: TypeError: Cannot read property 'innerHTML' of null
    at __pyppeteer_evaluation_script__

**Comment by FredHappyface** [comment]
Hi can you fill in the template please...

**Comment by FredHappyface** [comment]
closed due to inactivity
